"""create launch codes table

Revision ID: d8592db52794
Revises: 3b0f0e7b3fbc
Create Date: 2025-12-06 01:31:47.361463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8592db52794'
down_revision: Union[str, Sequence[str], None] = '3b0f0e7b3fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('game_sessions', sa.Column('game_id', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('game_sessions_user_id_fkey'), 'game_sessions', type_='foreignkey')
    op.create_foreign_key('game_sessions_user_id_fkey', 'game_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('inventory_items_prize_id_fkey'), 'inventory_items', type_='foreignkey')
    op.drop_constraint(op.f('inventory_items_user_id_fkey'), 'inventory_items', type_='foreignkey')
    op.create_foreign_key('inventory_items_prize_id_fkey', 'inventory_items', 'prizes', ['prize_id'], ['id'])
    op.create_foreign_key('inventory_items_user_id_fkey', 'inventory_items', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('token_qr_item_id_fkey'), 'token_qr', type_='foreignkey')
    op.drop_constraint(op.f('token_qr_user_id_fkey'), 'token_qr', type_='foreignkey')
    op.create_foreign_key('token_qr_item_id_fkey', 'token_qr', 'inventory_items', ['item_id'], ['id'])
    op.create_foreign_key('token_qr_user_id_fkey', 'token_qr', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_users_team_id'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_team_id', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_team_id'), 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('token_qr_user_id_fkey', 'token_qr', type_='foreignkey')
    op.drop_constraint('token_qr_item_id_fkey', 'token_qr', type_='foreignkey')
    op.create_foreign_key(op.f('token_qr_user_id_fkey'), 'token_qr', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('token_qr_item_id_fkey'), 'token_qr', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('inventory_items_user_id_fkey', 'inventory_items', type_='foreignkey')
    op.drop_constraint('inventory_items_prize_id_fkey', 'inventory_items', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_items_user_id_fkey'), 'inventory_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inventory_items_prize_id_fkey'), 'inventory_items', 'prizes', ['prize_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('game_sessions_user_id_fkey', 'game_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('game_sessions_user_id_fkey'), 'game_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('game_sessions', 'game_id')
    op.drop_table('launch_codes')
    # ### end Alembic commands ###
