"""transfer user columns

Revision ID: fa987870e5e1
Revises: a629654c84b7
Create Date: 2025-12-05 21:41:29.436221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa987870e5e1'
down_revision: Union[str, Sequence[str], None] = 'a629654c84b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('max_score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('energy', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'role')
    op.drop_column('users', 'energy')
    op.drop_column('users', 'amount')
    op.drop_column('users', 'level')
    op.drop_column('users', 'score')
    op.drop_column('users', 'max_score')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
